export const IM_GOOD_AT_TAGS = [
  // 'Docker',
  // 'JavaScript',
  // 'MongoDB',
  // 'NodeJS',
  // 'ReactJS',
  // 'Unix',
  // 'MySQL',
  // 'PostgreSQL',
  // 'Docker',
  // 'GraphQL',
  // 'TypeScript',
  'Communication',
  'Standardization',
  'Problem solving',
  'Web development',
  'Data migration',
  'System migration',
  'Software designing',
  'Interviewing',
]
