export const IM_GOOD_AT_TAGS = [
  'Communication',
  'Standardization',
  'Problem solving',
  'Web development',
  'Data migration',
  'System migration',
  'Software designing',
  'Interviewing',
  'App observability',
  'Tech debt management',
  'Overprovision reduction',
]

export const TECHNOLOGIES = [
  'JavaScript',
  'TypeScript',
  'NodeJS',
  'MongoDB',
  'MySQL',
  'GraphQL',
  'ReactJS',
  'Unix',
  'Bash scripting',
  'Docker',
  'Kubernetes',
  'AWS',
  'GCP',
  'CI/CD',
]
